return PlaceObj('ModDef', {
	'title', "Tool Bag",
	'description', "New Item: Tool Bag.\nCombines tool items to free up inventory space.\nFound in Ernie Village, Bobby Ray's and tool dropping containers.",
	'image', "Mod/rnPcbK/Images/Preview_Toolbag.jpg",
	'last_changes', "v0.9\nFixed Crowbar Lockpick Toolbag being locked.",
	'id', "rnPcbK",
	'author', "Timmeh",
	'version_minor', 9,
	'version', 104,
	'lua_revision', 233360,
	'saved_with_revision', 346319,
	'code', {
		"Code/ToolBagCombinations.lua",
		"Code/ToolBagDisassembleExplosives.lua",
		"Code/ToolBagEnabler.lua",
		"InventoryItem/ToolBag.lua",
		"InventoryItem/ToolBag_Crowbar.lua",
		"InventoryItem/ToolBag_Crowbar_Lockpick.lua",
		"InventoryItem/ToolBag_Crowbar_Wirecutter.lua",
		"InventoryItem/ToolBag_Crowbar_Lockpick_Wirecutter.lua",
		"InventoryItem/ToolBag_Lockpick.lua",
		"InventoryItem/ToolBag_Wirecutter.lua",
		"InventoryItem/ToolBag_Lockpick_Wirecutter.lua",
	},
	'saved', 1702227092,
	'code_hash', -8335637587613352941,
	'steam_id', "3026346564",
	'TagWeapons&Items', true,
})
